<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $features = [
            'House' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Double Glazed Windows' => ['type' => 'checkbox', 'icon' => 'fal fa-window-frame-open'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Furnished' => ['type' => 'checkbox', 'icon' => 'fal fa-loveseat'],
                ],
                'Rooms' => [
                    'Bedrooms' => ['type' => 'number', 'icon' => 'fal fa-bed-alt'],
                    'Bathrooms' => ['type' => 'number', 'icon' => 'fal fa-bathtub'],
                    'Servant Quarters' => ['type' => 'number', 'icon' => 'fal fa-house'],
                    'Drawing Room' => ['type' => 'checkbox', 'icon' => 'fal fa-couch'],
                    'Dining Room' => ['type' => 'checkbox', 'icon' => 'fal fa-utensils-alt'],
                    'Kitchens' => ['type' => 'number', 'icon' => 'fal fa-utensils'],
                    'Study Room' => ['type' => 'checkbox', 'icon' => 'fal fa-books'],
                    'Prayer Room' => ['type' => 'checkbox', 'icon' => 'fal fa-mosque'],
                    'Powder Room' => ['type' => 'checkbox', 'icon' => 'far fa-toothbrush'],
                    'Gym' => ['type' => 'checkbox', 'icon' => 'fal fa-dumbbell'],
                    'Store Rooms' => ['type' => 'number', 'icon' => 'fal fa-warehouse-alt'],
                    'Steam Room' => ['type' => 'checkbox', 'icon' => 'fal fa-heat'],
                    'Lounge or Sitting Room' => ['type' => 'checkbox', 'icon' => 'fal fa-chair'],
                    'Laundry Room' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Healthcare Recreational' => [
                    'Lawn or Garden' => ['type' => 'checkbox', 'icon' => 'fal fa-tree-alt'],
                    'Swimming Pool' => ['type' => 'checkbox', 'icon' => 'fal fa-swimming-pool'],
                    'Sauna' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Jacuzzi' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Other Healthcare and Recreation Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ]
            ],
            'Flat' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Lobby in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-building'],
                    'Double Glazed Windows' => ['type' => 'checkbox', 'icon' => 'fal fa-window-frame-open'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floor' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Floors in Building' => ['type' => 'number', 'icon' => 'fal fa-building'],
                    'Elevator' => ['type' => 'text', 'icon' => 'fal fa-sort-circle'],
                    'Service Elevator in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Furnished' => ['type' => 'checkbox', 'icon' => 'fal fa-loveseat'],
                ],
                'Rooms' => [
                    'Bedrooms' => ['type' => 'number', 'icon' => 'fal fa-bed-alt'],
                    'Bathrooms' => ['type' => 'number', 'icon' => 'fal fa-bath'],
                    'Servant Quarters' => ['type' => 'number', 'icon' => 'fal fa-house'],
                    'Drawing Room' => ['type' => 'checkbox', 'icon' => 'fal fa-couch'],
                    'Dining Room' => ['type' => 'checkbox', 'icon' => 'fal fa-utensils-alt'],
                    'Kitchens' => ['type' => 'number', 'icon' => 'fal fa-utensils'],
                    'Study Room' => ['type' => 'checkbox', 'icon' => 'fal fa-books'],
                    'Prayer Room' => ['type' => 'checkbox', 'icon' => 'fal fa-mosque'],
                    'Powder Room' => ['type' => 'checkbox', 'icon' => 'far fa-toothbrush'],
                    'Gym' => ['type' => 'checkbox', 'icon' => 'fal fa-dumbbell'],
                    'Store Rooms' => ['type' => 'number', 'icon' => 'fal fa-warehouse-alt'],
                    'Steam Room' => ['type' => 'checkbox', 'icon' => 'fal fa-heat'],
                    'Lounge or Sitting Room' => ['type' => 'checkbox', 'icon' => 'fal fa-chair'],
                    'Laundry Room' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Business Center or Media Room in Building' => ['type' => 'checkbox', 'icon' => 'far fa-phone-laptop'],
                    'Conference Room in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-camera-home'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'ATM Machines' => ['type' => 'checkbox', 'icon' => 'fal fa-calculator'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Healthcare Recreational' => [
                    'Sauna' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Jacuzzi' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Other Healthcare and Recreation Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Laundry or Dry Cleaning Facility' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Communal/Shared Kitchen' => ['type' => 'checkbox', 'icon' => 'fal fa-utensils'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Pet Policy' => ['type' => 'select', 'options' => ['Allowed', 'Not Allowed'], 'icon' => 'fal fa-paw-alt'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ]
            ],
            'Upper Portion' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Double Glazed Windows' => ['type' => 'checkbox', 'icon' => 'fal fa-window-frame-open'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Furnished' => ['type' => 'checkbox', 'icon' => 'fal fa-loveseat'],
                ],
                'Rooms' => [
                    'Bedrooms' => ['type' => 'number', 'icon' => 'fal fa-bed-alt'],
                    'Bathrooms' => ['type' => 'number', 'icon' => 'fal fa-bath'],
                    'Servant Quarters' => ['type' => 'number', 'icon' => 'fal fa-house'],
                    'Drawing Room' => ['type' => 'checkbox', 'icon' => 'fal fa-couch'],
                    'Dining Room' => ['type' => 'checkbox', 'icon' => 'fal fa-utensils-alt'],
                    'Kitchens' => ['type' => 'number', 'icon' => 'fal fa-utensils'],
                    'Study Room' => ['type' => 'checkbox', 'icon' => 'fal fa-books'],
                    'Prayer Room' => ['type' => 'checkbox', 'icon' => 'fal fa-mosque'],
                    'Powder Room' => ['type' => 'checkbox', 'icon' => 'far fa-toothbrush'],
                    'Gym' => ['type' => 'checkbox', 'icon' => 'fal fa-dumbbell'],
                    'Store Rooms' => ['type' => 'number', 'icon' => 'fal fa-warehouse-alt'],
                    'Steam Room' => ['type' => 'checkbox', 'icon' => 'fal fa-heat'],
                    'Lounge or Sitting Room' => ['type' => 'checkbox', 'icon' => 'fal fa-chair'],
                    'Laundry Room' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Healthcare Recreational' => [
                    'Lawn or Garden' => ['type' => 'checkbox', 'icon' => 'fal fa-tree-alt'],
                    'Swimming Pool' => ['type' => 'checkbox', 'icon' => 'fal fa-swimming-pool'],
                    'Sauna' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Jacuzzi' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Other Healthcare and Recreation Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ]
            ],
            'Lower Portion' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Double Glazed Windows' => ['type' => 'checkbox', 'icon' => 'fal fa-window-frame-open'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Furnished' => ['type' => 'checkbox', 'icon' => 'fal fa-loveseat'],
                ],
                'Rooms' => [
                    'Bedrooms' => ['type' => 'number', 'icon' => 'fal fa-bed-alt'],
                    'Bathrooms' => ['type' => 'number', 'icon' => 'fal fa-bath'],
                    'Servant Quarters' => ['type' => 'number', 'icon' => 'fal fa-house'],
                    'Drawing Room' => ['type' => 'checkbox', 'icon' => 'fal fa-couch'],
                    'Dining Room' => ['type' => 'checkbox', 'icon' => 'fal fa-utensils-alt'],
                    'Kitchens' => ['type' => 'number', 'icon' => 'fal fa-utensils'],
                    'Study Room' => ['type' => 'checkbox', 'icon' => 'fal fa-books'],
                    'Prayer Room' => ['type' => 'checkbox', 'icon' => 'fal fa-mosque'],
                    'Powder Room' => ['type' => 'checkbox', 'icon' => 'far fa-toothbrush'],
                    'Gym' => ['type' => 'checkbox', 'icon' => 'fal fa-dumbbell'],
                    'Store Rooms' => ['type' => 'number', 'icon' => 'fal fa-warehouse-alt'],
                    'Steam Room' => ['type' => 'checkbox', 'icon' => 'fal fa-heat'],
                    'Lounge or Sitting Room' => ['type' => 'checkbox', 'icon' => 'fal fa-chair'],
                    'Laundry Room' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Healthcare Recreational' => [
                    'Lawn or Garden' => ['type' => 'checkbox', 'icon' => 'fal fa-tree-alt'],
                    'Swimming Pool' => ['type' => 'checkbox', 'icon' => 'fal fa-swimming-pool'],
                    'Sauna' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Jacuzzi' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Other Healthcare and Recreation Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ]
            ],
            'Farm House' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
//                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Double Glazed Windows' => ['type' => 'checkbox', 'icon' => 'fal fa-window-frame-open'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Furnished' => ['type' => 'checkbox', 'icon' => 'fal fa-loveseat'],
                ],
                'Rooms' => [
                    'Bedrooms' => ['type' => 'number', 'icon' => 'fal fa-bed-alt'],
                    'Bathrooms' => ['type' => 'number', 'icon' => 'fal fa-bathtub'],
                    'Servant Quarters' => ['type' => 'number', 'icon' => 'fal fa-house'],
                    'Drawing Room' => ['type' => 'checkbox', 'icon' => 'fal fa-couch'],
                    'Dining Room' => ['type' => 'checkbox', 'icon' => 'fal fa-utensils-alt'],
                    'Kitchens' => ['type' => 'number', 'icon' => 'fal fa-utensils'],
                    'Study Room' => ['type' => 'checkbox', 'icon' => 'fal fa-books'],
                    'Prayer Room' => ['type' => 'checkbox', 'icon' => 'fal fa-mosque'],
                    'Powder Room' => ['type' => 'checkbox', 'icon' => 'far fa-toothbrush'],
                    'Gym' => ['type' => 'checkbox', 'icon' => 'fal fa-dumbbell'],
                    'Store Rooms' => ['type' => 'number', 'icon' => 'fal fa-warehouse-alt'],
                    'Steam Room' => ['type' => 'checkbox', 'icon' => 'fal fa-heat'],
                    'Lounge or Sitting Room' => ['type' => 'checkbox', 'icon' => 'fal fa-chair'],
                    'Laundry Room' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Healthcare Recreational' => [
                    'Lawn or Garden' => ['type' => 'checkbox', 'icon' => 'fal fa-tree-alt'],
                    'Swimming Pool' => ['type' => 'checkbox', 'icon' => 'fal fa-swimming-pool'],
                    'Sauna' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Jacuzzi' => ['type' => 'checkbox', 'icon' => 'fal fa-hot-tub'],
                    'Other Healthcare and Recreation Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ]
            ],
            'Room' => [],
            'Penthouse' => [],
            'Residential Plot' => [
                'Plot Features' => [
                    'Possession' => ['type' => 'checkbox', 'icon' => 'fal fa-hand-holding-medical'],
                    'Corner' => ['type' => 'checkbox', 'icon' => 'fal fa-ruler-triangle'],
                    'Park Facing' => ['type' => 'checkbox', 'icon' => 'fal fa-trees'],
                    'Disputed' => ['type' => 'checkbox', 'icon' => 'fal fa-handshake-alt-slash'],
                    'File' => ['type' => 'checkbox', 'icon' => 'fal fa-file-alt'],
                    'Balloted' => ['type' => 'checkbox', 'icon' => 'fas fa-box-ballot'],
                    'Sewerage' => ['type' => 'checkbox', 'icon', 'fad fa-prescription-bottle'],
                    'Electricity' => ['type' => 'checkbox', 'icon' => 'fal fa-bolt'],
                    'Water Supply' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Water Well or Bore' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Sui Gas' => ['type' => 'checkbox', 'icon' => 'fal fa-sensor-fire'],
                    'Boundary Wall' => ['type' => 'checkbox', 'icon' => 'far fa-crop-alt'],
                    'Other Plot Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Commercial Plot' => [
                'Plot Features' => [
                    'Possession' => ['type' => 'checkbox', 'icon' => 'fal fa-hand-holding-medical'],
                    'Corner' => ['type' => 'checkbox', 'icon' => 'fal fa-ruler-triangle'],
                    'Park Facing' => ['type' => 'checkbox', 'icon' => 'fal fa-trees'],
                    'Disputed' => ['type' => 'checkbox', 'icon' => 'fal fa-handshake-alt-slash'],
                    'File' => ['type' => 'checkbox', 'icon' => 'fal fa-file-alt'],
                    'Balloted' => ['type' => 'checkbox', 'icon' => 'fas fa-box-ballot'],
                    'Sewerage' => ['type' => 'checkbox', 'icon', 'fad fa-prescription-bottle'],
                    'Electricity' => ['type' => 'checkbox', 'icon' => 'fal fa-bolt'],
                    'Water Supply' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Water Well or Bore' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Sui Gas' => ['type' => 'checkbox', 'icon' => 'fal fa-sensor-fire'],
                    'Boundary Wall' => ['type' => 'checkbox', 'icon' => 'far fa-crop-alt'],
                    'Other Plot Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Agricultural Land' => [
                'Plot Features' => [
                    'Possession' => ['type' => 'checkbox', 'icon' => 'fal fa-hand-holding-medical'],
                    'Disputed' => ['type' => 'checkbox', 'icon' => 'fal fa-handshake-alt-slash'],
                    'Electricity' => ['type' => 'checkbox', 'icon' => 'fal fa-bolt'],
                    'Sui Gas' => ['type' => 'checkbox', 'icon' => 'fal fa-sensor-fire'],
                    'Water Supply' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Water Well or Bore' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Irrigation' => ['type' => 'checkbox', 'icon' => 'fal fa-sprinkler'],
                    'Tube Well' => ['type' => 'checkbox', 'icon' => 'fal fa-faucet-drip'],
                    'Accessible by Road' => ['type' => 'checkbox', 'icon' => 'fal fa-road'],
                    'Perimeter Fencing' => ['type' => 'checkbox', 'icon' => 'fal fa-draw-square'],
                    'Land Fertility' => ['type' => 'checkbox', 'icon' => 'fal fa-seedling'],
                    'Boundary Lines' => ['type' => 'checkbox', 'icon' => 'fal fa-draw-square'],
                    'Nearby Water Resources' => ['type' => 'text', 'icon' => 'fal fa-water'],
                    'Other Plot Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Industrial Land' => [],
            'Plot File' => [],
            'Plot Form' => [],
            'Office' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Lobby in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-building'],
                    'Double Glazed Windows' => ['type' => 'checkbox', 'icon' => 'fal fa-window-frame-open'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floor' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Floors in Building' => ['type' => 'number', 'icon' => 'fal fa-building'],
                    'Service Elevator in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Furnished' => ['type' => 'checkbox', 'icon' => 'fal fa-loveseat'],
                ],
                'Rooms' => [
                    'Rooms' => ['type' => 'number', 'icon' => 'fal fa-home-lg-alt'],
                    'Servant Quarters' => ['type' => 'number', 'icon' => 'fal fa-house'],
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Business Center or Media Room in Building' => ['type' => 'checkbox', 'icon' => 'far fa-phone-laptop'],
                    'Conference Room in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-camera-home'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'ATM Machines' => ['type' => 'checkbox', 'icon' => 'fal fa-calculator'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Healthcare Recreational' => [
                    'Lawn or Garden' => ['type' => 'checkbox', 'icon' => 'fal fa-tree-alt'],
                    'Other Healthcare and Recreation Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Pet Policy' => ['type' => 'select', 'options' => ['Allowed', 'Not Allowed'], 'icon' => 'fal fa-paw-alt'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Shop' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'View' => ['type' => 'number', 'icon' => 'fal fa-home-lg'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floor' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Floors in Building' => ['type' => 'number', 'icon' => 'fal fa-building'],
                    'Service Elevator in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Rooms' => [
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'ATM Machines' => ['type' => 'checkbox', 'icon' => 'fal fa-calculator'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Warehouse' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Elevator or Lift' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Rooms' => [
                    'Other Rooms' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Factory' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors' => ['type' => 'number', 'icon' => 'fal fa-vihara'],
                    'Elevator or Lift' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Building' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Public Parking' => ['type' => 'checkbox', 'icon' => 'fal fa-parking-circle'],
                    'Underground Parking' => ['type' => 'checkbox', 'icon' => 'fal fa-parking-circle'],
                    'Lobby in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-building'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors in Building' => ['type' => 'number', 'icon' => 'fal fa-building'],
                    'Elevator or Lift' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Elevators' => ['type' => 'number', 'icon' => 'fal fa-sort-circle'],
                    'Service Elevator in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Number of Units' => ['type' => 'number', 'icon' => 'fal fa-building'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Business Center or Media Room in Building' => ['type' => 'checkbox', 'icon' => 'far fa-phone-laptop'],
                    'Conference Room in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-camera-home'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'ATM Machines' => ['type' => 'checkbox', 'icon' => 'fal fa-calculator'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'Laundry or Dry Cleaning Facility' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Pet Policy' => ['type' => 'select', 'options' => ['Allowed', 'Not Allowed'], 'icon' => 'fal fa-paw-alt'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
            'Other' => [
                'Main Features' => [
                    'Built in year' => ['type' => 'number', 'icon' => 'fal fa-calendar'],
                    'Parking Spaces' => ['type' => 'number', 'icon' => 'fal fa-garage-car'],
                    'Public Parking' => ['type' => 'checkbox', 'icon' => 'fal fa-parking-circle'],
                    'Underground Parking' => ['type' => 'checkbox', 'icon' => 'fal fa-parking-circle'],
                    'Lobby in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-building'],
                    'Central Air Conditioning' => ['type' => 'checkbox', 'icon' => 'fal fa-air-conditioner'],
                    'Central Heating' => ['type' => 'checkbox', 'icon' => 'fal fa-fireplace'],
                    'Flooring' => ['type' => 'select', 'options' => ['Tiles', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other'], 'icon' => 'fab fa-trello'],
                    'Electricity Backup' => ['type' => 'select', 'options' => ['None', 'Generator', 'UPS', 'Solar', 'Other'], 'icon' => 'fal fa-car-battery'],
                    'Waste Disposal' => ['type' => 'checkbox', 'icon' => 'fas fa-trash-alt'],
                    'Floors in Building' => ['type' => 'number', 'icon' => 'fal fa-building'],
                    'Elevator or Lift' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Elevators' => ['type' => 'number', 'icon' => 'fal fa-sort-circle'],
                    'Service Elevator in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-sort-circle'],
                    'Other Main Features' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                    'Number of Units' => ['type' => 'number', 'icon' => 'fal fa-building'],
                ],
                'Business and Communication' => [
                    'Broadband Internet Access' => ['type' => 'checkbox', 'icon' => 'fal fa-wifi'],
                    'Satellite or Cable TV Ready' => ['type' => 'checkbox', 'icon' => 'fal fa-tv'],
                    'Business Center or Media Room in Building' => ['type' => 'checkbox', 'icon' => 'far fa-phone-laptop'],
                    'Conference Room in Building' => ['type' => 'checkbox', 'icon' => 'fal fa-camera-home'],
                    'Intercom' => ['type' => 'checkbox', 'icon' => 'fal fa-phone-office'],
                    'ATM Machines' => ['type' => 'checkbox', 'icon' => 'fal fa-calculator'],
                    'Other Business and Communication Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Nearby Locations and Other Facilities' => [
                    'Nearby Schools' => ['type' => 'text', 'icon' => 'fal fa-graduation-cap'],
                    'Nearby Hospitals' => ['type' => 'text', 'icon' => 'fal fa-hospital'],
                    'Nearby Shopping Malls' => ['type' => 'text', 'icon' => 'fal fa-shopping-cart'],
                    'Nearby Restaurants' => ['type' => 'text', 'icon' => 'fal fa-burger-soda'],
                    'Distance From Airport (kms)' => ['type' => 'text', 'icon' => 'fal fa-plane-departure'],
                    'Nearby Public Transport Service' => ['type' => 'text', 'icon' => 'fal fa-car-bus'],
                    'Other Nearby Places' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
                'Other Facilities' => [
                    'Maintenance Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-tools'],
                    'Security Staff' => ['type' => 'checkbox', 'icon' => 'fal fa-user-tie'],
                    'CCTV Security' => ['type' => 'checkbox', 'icon' => 'fal fa-cctv'],
                    'Cafeteria/Canteen' => ['type' => 'checkbox', 'icon' => 'fal fa-coffee'],
                    'Laundry or Dry Cleaning Facility' => ['type' => 'checkbox', 'icon' => 'fal fa-washer'],
                    'Facilities for Disabled' => ['type' => 'checkbox', 'icon' => 'fal fa-blind'],
                    'Pet Policy' => ['type' => 'select', 'options' => ['Allowed', 'Not Allowed'], 'icon' => 'fal fa-paw-alt'],
                    'Other Facilities' => ['type' => 'text', 'icon' => 'fal fa-ellipsis-h'],
                ],
            ],
        ];

        DB::table('features')->truncate();

        foreach ($features as $key => $value) {
            DB::table('features')->insert([
                'name' => $key,
                'list' => json_encode($value),
            ]);
        }
    }
}
