<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HousingAuthoritiesCities extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array([
            "ID" => 75,
            "Title" => "ABDUL HAKEEM",
            "Description" => "Abdul Hakeem",
            "IsActive" => true,
            "Notification" => null,
            "CreatedDate" => null,
            "CreatedBy" => null,
            "ModifiedDate" => null,
            "ModifiedBy" => null

        ],
            [
                "ID" => 53,
                "Code" => null,
                "Title" => "AHMADPUR",
                "Description" => "Ahmadpur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 79,
                "Code" => null,
                "Title" => "ARIFWALA",
                "Description" => "Arifwala",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 91,
                "Code" => null,
                "Title" => "ATTOCK",
                "Description" => "Attock",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 46,
                "Code" => null,
                "Title" => "BAHAWALNAGAR",
                "Description" => "Bahawalnagar City",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 45,
                "Code" => null,
                "Title" => "BAHAWALPUR",
                "Description" => "Bahawalpur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 92,
                "Code" => null,
                "Title" => "BHAKHAR",
                "Description" => "Bhakhar",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 97,
                "Code" => null,
                "Title" => "BHALWAL",
                "Description" => "Bhalwal",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 78,
                "Code" => null,
                "Title" => "BUREWALA",
                "Description" => "Burewala",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 90,
                "Code" => null,
                "Title" => "CHENABNAGAR",
                "Description" => "Chenabnagar",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 77,
                "Code" => null,
                "Title" => "CHICHAWATNI",
                "Description" => "Chichawatni",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 32,
                "Code" => null,
                "Title" => "CHINIOT",
                "Description" => "Chiniot",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 51,
                "Code" => null,
                "Title" => "CHISHTIAN",
                "Description" => "Chishtian",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 89,
                "Code" => null,
                "Title" => "DARYA KHAN",
                "Description" => "Darya Khan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 67,
                "Code" => null,
                "Title" => "DEPALPUR",
                "Description" => "Depalpur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 44,
                "Code" => null,
                "Title" => "DG KHAN",
                "Description" => "DG Khan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 73,
                "Code" => null,
                "Title" => "DUNYAPUR",
                "Description" => "Dunyapur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 43,
                "Code" => null,
                "Title" => "FAISALABAD",
                "Description" => "Faisalabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 70,
                "Code" => null,
                "Title" => "FAROOQABAD",
                "Description" => "Farooqabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 49,
                "Code" => null,
                "Title" => "FORTABBAS",
                "Description" => "Fortabbas",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 58,
                "Code" => null,
                "Title" => "FORTMANRO",
                "Description" => "Fortmanro",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 62,
                "Code" => null,
                "Title" => "GOJRA",
                "Description" => "Gojra",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 80,
                "Code" => null,
                "Title" => "GUJARKHAN",
                "Description" => "Gujarkhan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 41,
                "Code" => null,
                "Title" => "GUJRANWALA",
                "Description" => "Gujranwala",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 38,
                "Code" => null,
                "Title" => "GUJRAT",
                "Description" => "Gujrat",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 20,
                "Code" => null,
                "Title" => "HAFIZABAD",
                "Description" => "Hafizabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 48,
                "Code" => null,
                "Title" => "HAROONABAD",
                "Description" => "Haroonabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 54,
                "Code" => null,
                "Title" => "HASILPUR",
                "Description" => "Hasilpur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 82,
                "Code" => null,
                "Title" => "HASSANABDAL",
                "Description" => "Hassanabdal",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 84,
                "Code" => null,
                "Title" => "HAZRO",
                "Description" => "Hazro",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 40,
                "Code" => null,
                "Title" => "ISLAMABAD",
                "Description" => "Islamabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 74,
                "Code" => null,
                "Title" => "JAHANIAN",
                "Description" => "Jahanian",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 76,
                "Code" => null,
                "Title" => "JALALPUR PIRWALA",
                "Description" => "Jalalpur pirwala",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 94,
                "Code" => null,
                "Title" => "JARANWALA",
                "Description" => "Jaranwala",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 86,
                "Code" => null,
                "Title" => "JAUHARABAD",
                "Description" => "Jauharabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 28,
                "Code" => null,
                "Title" => "JEHLUM",
                "Description" => "Jehlum",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 16,
                "Code" => null,
                "Title" => "JHANG",
                "Description" => "Jhang",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 85,
                "Code" => null,
                "Title" => "KALLURKOT",
                "Description" => "Kallurkot",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 63,
                "Code" => null,
                "Title" => "KAMALIA",
                "Description" => "Kamalia",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 31,
                "Code" => null,
                "Title" => "KASUR",
                "Description" => "Kasur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 55,
                "Code" => null,
                "Title" => "KHAIRPUR TAMIANWALI",
                "Description" => "Khairpur Tamianwali",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 22,
                "Code" => null,
                "Title" => "KHANEWAL",
                "Description" => "Khanewal",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 57,
                "Code" => null,
                "Title" => "KHANPUR",
                "Description" => "Khanpur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 35,
                "Code" => null,
                "Title" => "KHUSHAB",
                "Description" => "Khushab",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 1093,
                "Code" => null,
                "Title" => "KOTLI SATYAIN",
                "Description" => "Kotli Satyain",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 15,
                "Code" => null,
                "Title" => "LAHORE",
                "Description" => "Lahore",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 23,
                "Code" => null,
                "Title" => "LAYYAH",
                "Description" => "Layyah",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 88,
                "Code" => null,
                "Title" => "LIAQATABAD",
                "Description" => "Liaqatabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 39,
                "Code" => null,
                "Title" => "LODHRAN",
                "Description" => "Lodhran",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 95,
                "Code" => null,
                "Title" => "MAMUKANJAN",
                "Description" => "Mamukanjan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 37,
                "Code" => null,
                "Title" => "MANDI BAHAUDDIN",
                "Description" => "Mandi Bahauddin",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 33,
                "Code" => null,
                "Title" => "MIANWALI",
                "Description" => "Mianwali",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 50,
                "Code" => null,
                "Title" => "MINCHINABAD",
                "Description" => "Minchinabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 21,
                "Code" => null,
                "Title" => "MULTAN",
                "Description" => "Multan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 68,
                "Code" => null,
                "Title" => "MURIDKE",
                "Description" => "Muridke",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 1094,
                "Code" => null,
                "Title" => "MURREE",
                "Description" => "Murree",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 26,
                "Code" => null,
                "Title" => "MUZAFFARGARH",
                "Description" => "Muzaffargarh",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 47,
                "Code" => null,
                "Title" => "NANKANA SAHIB",
                "Description" => 'Nankana Sahib',
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 71,
                "Code" => null,
                "Title" => "NARANGMANDI",
                "Description" => "Narangmandi",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 30,
                "Code" => null,
                "Title" => "NAROWAL",
                "Description" => "Narowal",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 34,
                "Code" => null,
                "Title" => "OKARA",
                "Description" => "Okara One",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 18,
                "Code" => null,
                "Title" => "PAKPATTAN",
                "Description" => "Pakpattan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 64,
                "Code" => null,
                "Title" => "PASRUR",
                "Description" => "Pasrur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 65,
                "Code" => null,
                "Title" => "PATTOKI",
                "Description" => "Pattoki",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 61,
                "Code" => null,
                "Title" => "PIRMAHAL",
                "Description" => "Pirmahal",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 87,
                "Code" => null,
                "Title" => "QUAIDABAD",
                "Description" => "Quaidabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 25,
                "Code" => null,
                "Title" => "RAHIM YAR KHAN",
                "Description" => "Rahim Yar Khan",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 29,
                "Code" => null,
                "Title" => "RAJANPUR",
                "Description" => "Rajanpur",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 14,
                "Code" => null,
                "Title" => "RAWALPINDI",
                "Description" => "Rawalpindi",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 66,
                "Code" => null,
                "Title" => "RENALAKHURD",
                "Description" => "Renalakhurd",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 56,
                "Code" => null,
                "Title" => "SADIQABAD",
                "Description" => "Sadiqabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 42,
                "Code" => null,
                "Title" => "SAHIWAL",
                "Description" => "Sahiwal",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 69,
                "Code" => null,
                "Title" => "SANGLA",
                "Description" => "Sangla",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 19,
                "Code" => null,
                "Title" => "SARGODHA",
                "Description" => "Sargodha",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 27,
                "Code" => null,
                "Title" => "SHEIKHUPURA",
                "Description" => "Sheikhupura",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 60,
                "Code" => null,
                "Title" => "SHORKOT",
                "Description" => "Shorkot",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 72,
                "Code" => null,
                "Title" => "SHUJABAD",
                "Description" => "Shujabad",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 36,
                "Code" => null,
                "Title" => "SIALKOT",
                "Description" => "Sialkot",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 98,
                "Code" => null,
                "Title" => "SILLIANWALI",
                "Description" => "Sillianwali",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 93,
                "Code" => null,
                "Title" => "SUMMANDRI",
                "Description" => "Summandri",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 83,
                "Code" => null,
                "Title" => "TALAGANG",
                "Description" => "Talagang",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 96,
                "Code" => null,
                "Title" => "TANDLIANWALA",
                "Description" => "Tandlianwala",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 59,
                "Code" => null,
                "Title" => "TAUNSA",
                "Description" => "Taunsa",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 81,
                "Code" => null,
                "Title" => "TAXILA",
                "Description" => "Taxila",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 24,
                "Code" => null,
                "Title" => "TOBA TEK SINGH",
                "Description" => "Toba Tek Singh",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 17,
                "Code" => null,
                "Title" => "VEHARI",
                "Description" => "Vehari",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ],
            [
                "ID" => 52,
                "Code" => null,
                "Title" => "YAZMAN",
                "Description" => "Yazman",
                "IsActive" => true,
                "Notification" => null,
                "CreatedDate" => null,
                "CreatedBy" => null,
                "ModifiedDate" => null,
                "ModifiedBy" => null
            ]);


        DB::connection('mysql3')->table('cities')->truncate();

        foreach ($cities as $city) {
            DB::connection('mysql3')->table('cities')->insert(
                [
                    'title' => $city['Description'],
                    'is_active' => 1
                ]
            );
        }

    }
}
